// <auto-generated />
namespace MySoftCorporation.Data.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Modifying : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modifying));
        
        string IMigrationMetadata.Id
        {
            get { return "202102141458405_Modifying"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
