// <auto-generated />
namespace MySoftCorporation.Data.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Table_StudentLedgerAndStudentLedgerTransactionAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_StudentLedgerAndStudentLedgerTransactionAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202104141122332_Table_StudentLedgerAndStudentLedgerTransactionAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
