// <auto-generated />
namespace MySoftCorporation.Data.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class VoucherType_LocationParam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VoucherType_LocationParam));
        
        string IMigrationMetadata.Id
        {
            get { return "202104081615081_VoucherType_LocationParam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
